// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXMonY99gc7nGPKn4cOxSmkmeIsdVSAQ',
    appId: '1:825686175806:web:0bb7fb222d3a4e7ea1e16f',
    messagingSenderId: '825686175806',
    projectId: 'grocerylist-92b06',
    authDomain: 'grocerylist-92b06.firebaseapp.com',
    storageBucket: 'grocerylist-92b06.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBctduEZgooVy2DxRqSi22JRta2Ibo9TVU',
    appId: '1:825686175806:android:53333f99f15f72f5a1e16f',
    messagingSenderId: '825686175806',
    projectId: 'grocerylist-92b06',
    storageBucket: 'grocerylist-92b06.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaXMonY99gc7nGPKn4cOxSmkmeIsdVSAQ',
    appId: '1:825686175806:web:42b60a6e6adc7e82a1e16f',
    messagingSenderId: '825686175806',
    projectId: 'grocerylist-92b06',
    authDomain: 'grocerylist-92b06.firebaseapp.com',
    storageBucket: 'grocerylist-92b06.firebasestorage.app',
  );
}
